classDiagram
    Entity <|-- Repository
    Repository <|-- Service
    Service <|-- Controller  
    Entity <|-- Service
    Reponse <|-- Controller

    class Entity{
      +varchar team
      +int score
    }
    class Application
    
            